spring:
  application:
    name: hello-spring-cloud-web-feign
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: LEGACYHTML5
    servlet:
      content-type: text/html
server:
  port: 8765

feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

